<?php /** @var $helperAnyday Anyday_Paymentmethod_Helper_Anyday */ ?>
<?php $helperAnyday = Mage::helper('adpaymentmethod/anyday') ?>
<?php if ($helperAnyday->isPaymentAnyday($this->getOrder()->getPayment())): ?>
<?php if (!$helperAnyday->isFirstInvoice($this->getOrder()) && $helperAnyday->isOfflineInvoice($this->getOrder())): ?>
<script type="text/javascript">
//<![CDATA[
    var invoiceCaptureCaseOptions = $$('select[name="invoice[capture_case]"] option');
    for (var i = 0; i < invoiceCaptureCaseOptions.length; i++) {
        if (invoiceCaptureCaseOptions[i].value == 'online') {
            $$('select[name="invoice[capture_case]"]')[0].remove(i);
            break;
        }
    }
//]]>
</script>
<?php endif; ?>
<?php endif; ?>
